# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fatimazahrabouj
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ProductService

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  authorizers:
    myCognitoAuthorizer:
      identitySource: method.request.header.Authorization #extract jwt token from the Authorization header
      issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_MueruvOAq #Token signing key URL
      audience:
        - 4ohbb7ovv7jrnlc3qrmjs55qlv #App client id (ensure the token comes from the correct app)

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: product-images-fatima-zahra-bucket-123-dev

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          authorizer:
            name: myCognitoAuthorizer