# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fatimazahrabouj
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ProductService

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  environment:
    BUCKET_NAME: product-images-fatima-zahra-bucket-123-dev
    DYNAMO_TABLE_NAME: Products
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:520557389016:ProductCleanUpTopic
  httpApi:
    authorizers:
      myCognitoAuthorizer:
        identitySource: $request.header.Authorization #extract jwt token from the Authorization header
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_MueruvOAq #Token signing key URL
        audience:
          - 4ohbb7ovv7jrnlc3qrmjs55qlv #App client id (ensure the token comes from the correct app)
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::product-images-fatima-zahra-bucket-123-dev/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-east-1:520557389016:table/Products
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:us-east-1:520557389016:ProductCleanUpTopic

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: product-images-fatima-zahra-bucket-123-dev
    ProductCleanUpTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProductCleanUpTopic
    ProductCleanUpSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:us-east-1:520557389016:ProductCleanUpTopic
        Protocol: email
        Endpoint: fatima.z.bouj@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /get-upload-url
          method: post
          authorizer:
            name: myCognitoAuthorizer
  getApprovedProducts:
    handler: handlers/getApprovedProducts.getApprovedProducts
    events:
      - httpApi:
          path: /get-approved-products
          method: get
  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: product-images-fatima-zahra-bucket-123-dev #name of the S3 bucket
          event: s3:ObjectCreated:Put #trigger event when an object is created in the bucket
          existing: true #ensures the function works with an existing bucket
  cleanUpProducts:
    handler: handlers/cleanUpProducts.cleanUpProducts
    events:
      - schedule: rate(2 minutes) #runs every 2 minutes to clean up old images